### ISSUE TITLE
Format the tooltip of the main map 

### ISSUE THREAD

**Issue by cugarteblair** [SlideRuleEarth/sliderule-web-client#51]
Per JP's comment:
"If possible, I’d format the time as a date and UTC (or even timezone configurable) string.  Lastly, is it possible to put the pop up box at the bottom of the map, in the same place, regardless of where the cursor is?  If not, then I like the offset that you have, though maybe the box is a bit wide."

**Comment by mataleogml** [comment]
Carlos could you point me towards which tooltip on the map is having this issue, as I could not local a date or time on the map itself
