### ISSUE TITLE
Need to increase the contrast of Hover when hovering over the main tool menu

### ISSUE THREAD

**Issue by cugarteblair** [SlideRuleEarth/sliderule-web-client#66]
Map Record Analysis Docs and About 
These should have hover styling and hints.
Hints are neccesary because It is not obvious how to get back to the "Home"

**Comment by mataleogml** [comment]
This issue has been fix with #77 Appbar Button effects right?

**Comment by cugarteblair** [comment]
What do you think from a UX designer?
Increased contrast or border highlighting?
