### ISSUE TITLE
Make the Tool column scrollable

### ISSUE THREAD

**Issue by cugarteblair** [SlideRuleEarth/sliderule-web-client#69]
When you open the Advanced Tool items and scroll the entire page scrolls.
It would be nice if only the tool bar scrolled and the map stayed put.

**Comment by mataleogml** [comment]
I have a fix that would address this issue, but looking at the layout structure currently `SrRunControl` sits inside `SrAdvOptSidebar` and `SrGenUserSidebar `separately, where they are inside `SrSideBarLayout`'s `sr-sidebar-body` div.

`SrSideBarLayout` current layout is as follow
```
<template>
    <div class="sr-sidebar-header">
        <slot name = "sr-sidebar-header"></slot>
    </div>
    <div class="sr-sidebar-body">
        <slot name = "sr-sidebar-body"></slot>
    </div>
    <div class="sr-sidebar-footer">
        <slot name = "sr-sidebar-footer"></slot>
    </div>
</template>
```

It might be best if we move `SrRunControl` into `sr-sidebar-header` to reduce the complexity of the code

**Comment by mataleogml** [comment]
Also since the exisiting `SrGenUserSidebar` is really simple

```
<template>
    <div class="sr-gen-user-sidebar-container">
        <SrRunControl />
        <SrGenUserSidebarOptions />
    </div>
</template>
```

It might be worth just have a new script to call `SrGenUserSidebarOptions` / `SrAdvOptSidebar` on SrSideBarLayout level to reduce action need to pull all these component out (since they share dependency)

**Comment by cugarteblair** [comment]
done v0.0.31
