### ISSUE TITLE
Make the About screen a popup that does not change view

### ISSUE THREAD

**Issue by cugarteblair** [SlideRuleEarth/sliderule-web-client#72]
When clicking about and returning to the map everything is reset.
It would be better to display a popup that does not change the screen

**Comment by mataleogml** [comment]
@cugarteblair I could not reproduce this issue on my end, could you elaborate more on this issue

**Comment by cugarteblair** [comment]
If you draw a polygon on the map. then click about. then go back to the map. the poly will be gone because the map resets. A simple way to avoid that is to make the about screen a popup instead of a new page.

**Comment by mataleogml** [comment]
Ah got it will take a look later tonight and make this a priority

**Comment by jpswinski** [comment]
@cugarteblair and @mataleogml - right now the "About" page is just some build information, but in the future, it would be nice to have this page a full page of information about the SlideRule project and team.  What do you think about having the display label at the top left that holds the version information right now (it says "Beta v0.0.27" currently) be the something that if clicked shows a popup of the detailed version information that is currently displayed on the "About" page, and make the "About" page a placeholder for the full description of our project and team and remain as a routed to page?

**Comment by cugarteblair** [comment]
I like that idea.
